site_name: QGIS.бг докс
repo_url: https://github.com/qgisbg/docs
extra_css:
  - assets/consent.css
  - assets/qgisbg.css
extra_javascript:
  - https://unpkg.com/mermaid@8.9.2/dist/mermaid.min.js
  - https://cdn.jsdelivr.net/npm/cookies-eu-banner@2.0.1/dist/cookies-eu-banner.js
  - assets/consent.js
plugins:
  - awesome-pages: {}
  - search:
      lang:
        - ru
        - en
theme:
  language: bg
  name: material
  custom_dir: overrides
  logo: assets/qgis3_text_bg.svg
  favicon: assets/qgis3_notext.svg
  features:
    - navigation.instant
    - navigation.tabs
    - content.tabs.link
    - search.suggest
    - search.highlight
    - search.share
  palette:
    - scheme: default
      primary: green
      accent: green
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - footnotes
  - def_list
  - pymdownx.inlinehilite
  - pymdownx.highlight
  - smarty
  - markdown_captions
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.extra
  - pymdownx.escapeall
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - mdx_include
  - mdx_iconify:
      patterns:
        qgis:
          width: "36"
          height: "36"
          prefix: https://raw.githubusercontent.com/qgis/QGIS/master/images/themes/default/
          suffix: .svg
          check_suffix: True
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
nav:
  - index.md
  - 'Уики':
    - wiki/about.md
    - 'Формати':
      - ... | flat | wiki/formats/*.md
    - 'QGIS рецепти':
      - wiki/qgis/kak_da_instalirame_qgis_v_windows.md
      - wiki/qgis/kak_da_instalirame_qgis_v_ubuntu.md
      - wiki/qgis/otkude_da_namerim_geografski_danni_za_bulgaria.md
      - wiki/qgis/kak_da_izpolzvam_danni_ot_osm_s_quickosm.md
      - wiki/qgis/kak_da_filtrirame_i_pokazhem_samo_chast_ot_obektite.md
      - wiki/qgis/kak_da_smenim_proektsiyata_na_vektoren_sloy.md
      - wiki/qgis/kak_da_dobavim_novo_pole_na_vektoren_sloy.md
      - wiki/qgis/kak_da_iztriem_pole_ot_vektoren_sloy.md
      - wiki/qgis/kak_da_svarzhem_dannite_ot_dva_sloya.md
      - wiki/qgis/kak_da_izteglim_dem_s_opentopography.md
    - 'Ресурси':
      - ... | flat | wiki/resources/*.md
    - 'Организации':
      - ... | flat | wiki/organizations/*.md
    - 'Tехнологии':
      - ... | flat | wiki/technologies/*.md
    - wiki/precision_vs_accuracy.md
  - ... | gisintro/*.md
  - ... | external/*.md
  - ... | meta/*.md
  - ... | maps/oops/*.md
  - events/2025_foss4g_bg.md
